import { FieldMapping, SessionInfo, GenerationResult } from './types';

export const MOCK_DEMO_SESSION: SessionInfo = {
  sessionId: 'demo-session-882194',
  sourceDoc: {
    filename: 'Master_Services_Agreement_2026.pdf',
    sizeBytes: 1845200,
    format: 'pdf',
    pageCount: 14,
  },
  templateDoc: {
    filename: 'Executive_Contract_Summary_Template.docx',
    sizeBytes: 421000,
    format: 'docx',
    detectedFieldsCount: 8,
  },
  createdAt: new Date().toISOString(),
};

export const MOCK_FIELDS: FieldMapping[] = [
  {
    id: 'f-1',
    templateField: 'client_legal_name',
    label: 'Client Legal Entity',
    targetLocation: 'Header / Section 1.1',
    extractedValue: 'PT Global Teknologi Nusantara',
    confidence: 0.98,
    confidenceLevel: 'high',
    sourcePage: 1,
    sourceSnippet: '...entered into by and between PT Global Teknologi Nusantara, a corporation registered under the laws of Indonesia...',
    isEdited: false,
    isConfirmed: true,
    fieldType: 'text',
  },
  {
    id: 'f-2',
    templateField: 'vendor_legal_name',
    label: 'Vendor / Provider Name',
    targetLocation: 'Section 1.2',
    extractedValue: 'Apex Cloud Systems Pte. Ltd.',
    confidence: 0.96,
    confidenceLevel: 'high',
    sourcePage: 1,
    sourceSnippet: '...and Apex Cloud Systems Pte. Ltd., having its principal office at 71 Ayer Rajah Crescent, Singapore...',
    isEdited: false,
    isConfirmed: true,
    fieldType: 'text',
  },
  {
    id: 'f-3',
    templateField: 'effective_date',
    label: 'Effective Agreement Date',
    targetLocation: 'Section 2.1',
    extractedValue: '15 October 2026',
    confidence: 0.92,
    confidenceLevel: 'high',
    sourcePage: 2,
    sourceSnippet: 'The Effective Date of this Master Services Agreement shall be October 15, 2026.',
    isEdited: false,
    isConfirmed: true,
    fieldType: 'date',
  },
  {
    id: 'f-4',
    templateField: 'contract_value_usd',
    label: 'Total Contract Value (USD)',
    targetLocation: 'Pricing Schedule / Exhibit B',
    extractedValue: '$185,000.00',
    confidence: 0.89,
    confidenceLevel: 'high',
    sourcePage: 9,
    sourceSnippet: 'Total contract consideration across the 24-month duration is capped at US$ 185,000 net of withholding taxes.',
    isEdited: false,
    isConfirmed: false,
    fieldType: 'currency',
  },
  {
    id: 'f-5',
    templateField: 'governing_law_jurisdiction',
    label: 'Governing Law & Jurisdiction',
    targetLocation: 'Section 14.4',
    extractedValue: 'Laws of Singapore (SIAC Arbitration)',
    confidence: 0.84,
    confidenceLevel: 'high',
    sourcePage: 12,
    sourceSnippet: 'This Agreement is governed by Singapore law. Any dispute shall be resolved via arbitration at SIAC.',
    isEdited: false,
    isConfirmed: false,
    fieldType: 'text',
  },
  {
    id: 'f-6',
    templateField: 'liability_cap_clause',
    label: 'Limitation of Liability Cap',
    targetLocation: 'Section 11.2',
    extractedValue: '12 months fees paid preceding the incident',
    confidence: 0.72,
    confidenceLevel: 'medium',
    sourcePage: 8,
    sourceSnippet: 'Except for breach of confidentiality, total aggregate liability shall not exceed the fees paid in the twelve (12) months preceding the claim.',
    isEdited: false,
    isConfirmed: false,
    fieldType: 'text',
  },
  {
    id: 'f-7',
    templateField: 'notice_period_days',
    label: 'Termination Notice Period (Days)',
    targetLocation: 'Section 7.3',
    extractedValue: '60 days prior written notice',
    confidence: 0.68,
    confidenceLevel: 'medium',
    sourcePage: 5,
    sourceSnippet: 'Either party may terminate for convenience upon sixty (60) days advance written notice.',
    isEdited: false,
    isConfirmed: false,
    fieldType: 'text',
  },
  {
    id: 'f-8',
    templateField: 'data_protection_officer_email',
    label: 'DPO Contact Email',
    targetLocation: 'Schedule D - Privacy',
    extractedValue: 'privacy@apexcloud.io',
    confidence: 0.45,
    confidenceLevel: 'low',
    sourcePage: 14,
    sourceSnippet: 'Notices regarding GDPR/PDPA may be directed to our compliance representative at privacy@apexcloud.io',
    isEdited: false,
    isConfirmed: false,
    fieldType: 'text',
  },
];

export const MOCK_GENERATION: GenerationResult = {
  sessionId: 'demo-session-882194',
  downloadUrl: '#',
  filename: 'Executive_Contract_Summary_Filled.docx',
  fileSizeBytes: 438200,
  format: 'docx',
  generatedAt: new Date().toISOString(),
};
