"""Shared account-tier credential verification (Phase 6, ADR-020).

One fixed username/password pair gates the account tier. The password is
never stored — only a salted scrypt hash in TIER_ACCOUNT_PASSWORD_HASH:

    scrypt$<salt_hex>$<hash_hex>

Generated by ``scripts/hash_password.py``. scrypt is stdlib (hashlib), so no
new dependency is introduced (same rationale as ADR-019).
"""

from __future__ import annotations

import hashlib
import hmac
import secrets

_N = 2**14
_R = 8
_P = 1
_DKLEN = 32
_PREFIX = "scrypt"


def hash_password(password: str) -> str:
    """Return a salted scrypt hash string for `password`."""
    salt = secrets.token_bytes(16)
    derived = hashlib.scrypt(
        password.encode("utf-8"), salt=salt, n=_N, r=_R, p=_P, dklen=_DKLEN
    )
    return f"{_PREFIX}${salt.hex()}${derived.hex()}"


def verify_password(password: str, stored: str) -> bool:
    """Constant-time check of `password` against a stored scrypt hash.

    Malformed/empty stored values return False (never raise) so a
    misconfigured env var fails closed.
    """
    if not password or not stored:
        return False
    try:
        prefix, salt_hex, hash_hex = stored.strip().split("$", 2)
        if prefix != _PREFIX:
            return False
        salt = bytes.fromhex(salt_hex)
        expected = bytes.fromhex(hash_hex)
    except (ValueError, AttributeError):
        return False
    derived = hashlib.scrypt(
        password.encode("utf-8"), salt=salt, n=_N, r=_R, p=_P, dklen=_DKLEN
    )
    return hmac.compare_digest(derived, expected)


__all__ = ["hash_password", "verify_password"]
